spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/MyPostSQL
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com.cai.quartzandactiviti: debug


bpmn:
  filePath: processes



user:
  home: C:\Users\RuoLi
