spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti7?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: 123456
    username: root
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com.cai.quartzandactiviti: debug
