spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/myActiviti
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: false
#   不加无法触发定时器任务 xml文件加了不生效
    async-executor-activate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.cai.quartzandactiviti: debug


bpmn:
  fileClassPath: processes


# 上传路径
file:
  upload-path: F:\processes\
